[template]
src = "haproxy.tmpl"
dest = "/usr/local/etc/haproxy/haproxy.cfg"
#dest = "/tmp/haproxy.cfg"
keys = [ "/services" ]
owner = "root"
mode = "0644"
check_cmd = "/usr/local/sbin/haproxy -c -f {{.src}}"
reload_cmd = "/usr/local/sbin/service haproxy reload"
