[template]
src = "haproxy.tmpl"
dest = "/usr/local/etc/haproxy/haproxy.cfg"
keys = [ "/services" ]

check_cmd = "/usr/local/sbin/haproxy -c -f {{.src}}"
reload_cmd = "haproxy -D -f /usr/local/sbin/haproxy -p /var/run/haproxy.pid -sf $(cat /var/run/haproxy.pid)"
